# Generated by Django 5.0.6 on 2024-09-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_appointment_photo_appointment_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='photo',
        ),
        migrations.AddField(
            model_name='appointment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
