# Generated by Django 5.0.6 on 2024-09-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_appointment_photo_appointment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='review',
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
    ]
